Allow passing in dom elements
ace-diff/ace-diff pull request #17
Opened 2016-01-29 20:18 UTC by ianmetcalf

Thanks for creating this library.

These changes allow passing dom nodes in for left, right and gutter instead of id's. This allows more flexibility in how these elements are selected (i.e. using classes instead). These changes should be completely backward compatible.

Let me know if you want me to update the README / demos to include this and have any preference for how it's added.

2016-07-05 02:58 UTC, benkeen commented
Hey @ianmetcalf - I'm so sorry, I missed this PR. This is great stuff. If you're still up for it, yes, if you wouldn't mind updating the README, that'd be great. I think we could probably do without a demo, since it's functionally the same, but feel free to add one if you fancy it. 

Thanks again!

2018-02-19 13:15 UTC, JackuB commented
Resolved in #27 🎉

2018-02-19 13:15 UTC, closed without merging

2022-04-07 01:57 UTC, Nickrt36 commented
> Hey @ianmetcalf - I'm so sorry, I missed this PR. This is great stuff. If you're still up for it, yes, if you wouldn't mind updating the README, that'd be great. I think we could probably do without a demo, since it's functionally the same, but feel free to add one if you fancy it. 
> 
> Thanks again!
> 

- [ ] ```
> Update on my new place
```

2022-04-07 01:58 UTC, Nickrt36 requested changes
@Nickrt36